I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 115, in script
    "{i} и это именно мой панический призыв к властям произвести расследование дал толчок последующим событиям.{/i}"
OSError: Couldn't find file 'audio/voices/main/main30.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 115, in script
    "{i} и это именно мой панический призыв к властям произвести расследование дал толчок последующим событиям.{/i}"
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\display\core.py", line 4379, in interact_core
    renpy.audio.audio.periodic()
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1224, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1202, in periodic_thread_main
    periodic_pass()
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1144, in periodic_pass
    c.periodic()
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\audio\audio.py", line 534, in periodic
    topf = load(filename)
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "C:\wamp64\www\renpy-8.1.3-sdk\renpy\loader.py", line 833, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'audio/voices/main/main30.mp3'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
TheShadowoverInnsmouth 1.0
Mon Feb 12 22:04:22 2024
